CREATE TABLE IF NOT EXISTS cars (
  _id    SERIAL NOT NULL,
  brand TEXT   NOT NULL,
  model TEXT   NOT NULL,
  color TEXT,
  price DOUBLE PRECISION,
  CONSTRAINT cars_pkey PRIMARY KEY (_id),
  CONSTRAINT part_id FOREIGN KEY (_id)
  REFERENCES parts (_id) MATCH SIMPLE
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
);
