CREATE TABLE IF NOT EXISTS cars (
  id    SERIAL NOT NULL,
  brand TEXT   NOT NULL,
  model TEXT   NOT NULL,
  color TEXT,
  price DOUBLE PRECISION,
  CONSTRAINT cars_pkey PRIMARY KEY (id),
  CONSTRAINT part_id FOREIGN KEY (id)
  REFERENCES parts (id) MATCH SIMPLE
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
);
